modules/kewangan/models/YuranPaymentDetails.php
<?php

namespace app\modules\kewangan\models;

use Yii;
use app\models\LookupYurandaftar;

/**
 * This is the model class for table "yuran_payment_details".
 *
 * @property int $id
 * @property string $no_resit
 * @property string $jenis_yuran
 * @property string $jenis_pembayaran
 * @property string $pic_name
 * @property string $created_at
 * @property int $enter_by
 * @property string $update_at
 * @property int $update_by
 * @property double $jumlah_bayaran
 * @property double $jumlah_tunggakan
 * @property string $pelarasan
 * @property string $ulasan
 * @property double $pelarasan_tambahan
 * @property double $pelarasan_tolakan
 */
class YuranPaymentDetails extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'yuran_payment_details';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tarikh_bayaran','jumlah_bayaran','pic_name'],'required','message'=>'Ruangan {attribute} wajib diisi','on'=>'paymentprocess'],
            [['enter_by', 'update_by','daftarid'], 'integer'],
            [['jumlah_bayaran', 'jumlah_tunggakan', 'pelarasan_tambahan', 'pelarasan_tolakan'], 'number'],
            [['ulasan'], 'string'],
            [['no_resit', 'jenis_yuran', 'jenis_pembayaran', 'pic_name','no_rujukan_pindahan_wang'], 'string', 'max' => 255],
            [['created_at', 'update_at','tarikh_bayaran'], 'string', 'max' => 50],
            [['pelarasan'], 'string', 'max' => 10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'no_resit' => 'No Resit',
            'jenis_yuran' => 'Jenis Yuran',
            'jenis_pembayaran' => 'Jenis Pembayaran',
            'pic_name' => 'Nama Penerima',
            'created_at' => 'Created At',
            'enter_by' => 'Enter By',
            'update_at' => 'Update At',
            'update_by' => 'Update By',
            'jumlah_bayaran' => 'Jumlah Bayaran',
            'jumlah_tunggakan' => 'Jumlah Tunggakan',
            'pelarasan' => 'Pelarasan',
            'ulasan' => 'Ulasan',
            'pelarasan_tambahan' => 'Pelarasan Tambahan',
            'pelarasan_tolakan' => 'Pelarasan Tolakan',
        ];
    }

    public function getInv()
    {
        return $this->hasOne(YuranPendaftaran::className(),['id' =>'daftarid']);
    }

    public function getItempays()
    {
        return $this->hasMany(YuranPendaftaranDetail::className(),['payment_id'=>'id']);
    }
}

modules/kewangan/models/YuranPendaftaran.php
<?php

namespace app\modules\kewangan\models;

use Yii;

use app\models\LookupPusatPengajian;
use app\models\LookupYurandaftar;

use app\modules\hr\pelajar\models\MaklumatPelajarPenjaga;
use app\modules\kewangan\models\YuranPendaftaranDetail;
use app\modules\oldyuran\models\OldYuranDaftar;

/**
 * This is the model class for table "yuran_pendaftaran".
 *
 * @property int $id
 * @property int $idstd
 * @property string $invoice_no
 * @property string $tarikh_bayaran
 * @property int $pusat_pengajian
 * @property double $jumlah_yuran
 * @property double $jumlah_bayaran
 * @property double $yuran_tertunggak_daftar
 * @property int $tahun
 * @property int $tahap_pelajar
 * @property int $guru_kelas
 * @property int $guru_kanan
 * @property int $status_yuran
 * @property string $nota
 * @property int $jenis_pelajar
 * @property string $nama_penerima
 * @property string $jenis_bayaran
 * @property string $no_rujukan_pindahan_wang
 * @property double $pelarasan_tambahan
 * @property double $pelarasan_tolakan
 * @property string $created_at
 * @property string $updated_at
 * @property int $enter_by
 * @property int $update_by
 */
class YuranPendaftaran extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'yuran_pendaftaran';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            //validation based on scenario
            [['jenis_pelajar','tahap_pelajar'],'required','on'=>'addbill','message'=>'Ruangan {attribute} wajib diisi'],
            [['jenis_pelajar'],'required','on'=>'yuranregisterday','message'=>'Ruangan {attribute} wajib diisi'],
            [['jenis_pelajar','tahap_pelajar'],'required','on'=>'edityuran','message'=>'Ruangan {attribute} wajib diisi'],

            [['idstd', 'pusat_pengajian', 'tahun', 'tahap_pelajar', 'guru_kelas', 'guru_kanan', 'status_yuran', 'jenis_pelajar', 'enter_by', 'update_by'], 'integer'],
            [['jumlah_yuran', 'jumlah_bayaran', 'yuran_tertunggak_daftar', 'pelarasan'], 'number'],
            [['nota','ulasan_pelarasan'], 'string'],
            [['invoice_no', 'nama_penerima', 'jenis_bayaran'], 'string', 'max' => 255],
            [['tarikh_bayaran', 'created_at', 'updated_at'], 'string', 'max' => 50],
            [['no_rujukan_pindahan_wang'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'idstd' => 'Idstd',
            'invoice_no' => 'No. Invois',
            'tarikh_bayaran' => 'Tarikh Bayaran',
            'pusat_pengajian' => 'Pusat Pengajian',
            'jumlah_yuran' => 'Jumlah Yuran (RM)',
            'jumlah_bayaran' => 'Jumlah Bayaran (RM)',
            'yuran_tertunggak_daftar' => 'Yuran Tertunggak Daftar',
            'tahun' => 'Tahun',
            'tahap_pelajar' => 'Tahap Pelajar',
            'guru_kelas' => 'Guru Kelas',
            'guru_kanan' => 'Guru Kanan',
            'status_yuran' => 'Status Yuran',
            'nota' => 'Nota',
            'jenis_pelajar' => 'Jenis Pelajar',
            'nama_penerima' => 'Nama Penerima',
            'jenis_bayaran' => 'Jenis Bayaran',
            'no_rujukan_pindahan_wang' => 'No Rujukan Pindahan Wang',
            'pelarasan' => 'Pelarasan',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'enter_by' => 'Enter By',
            'update_by' => 'Update By',
        ];
    }

    public static function savebill($id,$jenis_pelajar)
    {
        $model = MaklumatPelajarPenjaga::findOne($id);
        $model2 = new YuranPendaftaran();

        if (isset($model)) {
            $model2->idstd = $model->id;
            $model2->created_at = date('Y-m-d h:i:s A');
            $model2->enter_by = Yii::$app->user->identity->id;
            $model2->tahun = date('Y');
            $model2->pusat_pengajian = $model->pusat_pengajian_id;
            $model2->status_yuran = 0;
            $model2->tahap_pelajar = $model->tahap_semasa;
            $model2->jenis_pelajar = $jenis_pelajar;

            $getInv = YuranPendaftaran::find()->where(['not', ['invoice_no' => null]])->orderBy(['id' => SORT_DESC])->limit(1)->one();

            if (empty($getInv['invoice_no'])) {
                $runninNo = 10000;
                $noinv = 'INV#'.$model2->namatahfiz->code_resit."-".$runninNo;
                //strlen
            } else {
                $len = strlen('INV#'.$model2->namatahfiz->code_resit) + 1; // count string length and plus 1 
                $qt = substr($getInv['invoice_no'], $len); //remove code tahfiz n dash (-)
                $new = $qt + 1; // plus 1 for new no of receipt
                $runninNo = $new;

                $noinv = 'INV#'.$model2->namatahfiz->code_resit."-".$runninNo;
            }

            $model2->invoice_no = $noinv;

            if ($model2->save()) {
                
                $yuran = LookupYurandaftar::find()
                        ->where(['tahap_pelajar'=>$model->tahap_semasa])
                        ->andWhere(['jenis_pelajar'=>$jenis_pelajar])
                        ->all();

                foreach ($yuran as $key => $value) {
                    $model3 = new YuranPendaftaranDetail;

                    $model3->item_daftar = $value->id;
                    $model3->price = $value->jumlah;
                    $model3->daftarid = $model2->id;
                    $model3->save();
                }
                //check yuran tertunggak tahun sebelum
                $oldyuran = OldYuranDaftar::find()
                            ->where(['id_pelajar'=>$id])
                            ->andWhere(['!=','yuran_tertunggak',0.00])
                            ->orderBy(['id'=>SORT_DESC])
                            ->one();

                if (isset($oldyuran)) {
                    $yuran_tertunggak = new YuranPendaftaranDetail();
                    $yuran_tertunggak->item_daftar = 27;
                    $yuran_tertunggak->price = $oldyuran->yuran_tertunggak;
                    $yuran_tertunggak->daftarid = $model2->id;
                    $yuran_tertunggak->save();
                }
                return $model2->id;
            }
        }
        else{
            return false;
        }
    }

    public function getNamatahfiz()
    {
        return $this->hasOne(LookupPusatPengajian::className(),['id' =>'pusat_pengajian']);
    }

    public function getNamastd()
    {
        return $this->hasOne(MaklumatPelajarPenjaga::className(),['id' =>'idstd']);
    }

    public function getDetails()
    {
        return $this->hasMany(YuranPendaftaranDetail::className(),['daftarid'=>'id'])->orderBy(['id'=>SORT_ASC]);
    }

    public function getPayments()
    {
        return $this->hasMany(YuranPaymentDetails::className(),['daftarid'=>'id']);
    }

    public function getBakitunggak()
    {
        $baki = ($this->jumlah_yuran - $this->jumlah_bayaran) + $this->pelarasan;

        return $baki;
    }

    public function getStatus()
    {
        if ($this->status_yuran == 1) {
           $status = 'Telah Dijana';
        }
        else if ($this->status_yuran == 2) {
           $status = 'Separa';
        }
        else if ($this->status_yuran == 3) {
            $status = 'Telah Bayar';
        }
        else if ($this->status_yuran == 0) {
           $status = 'Draf';
        }

        return $status;
    }

    public function getJenispelajar()
    {
        if ($this->jenis_pelajar == 1) {
            $jenis = 'Pelajar Baru';
        }
        elseif ($this->jenis_pelajar == 2) {
            $jenis = 'Pelajar Lama';
        }
        elseif ($this->jenis_pelajar == 3) {
            $jenis = 'Pelajar Lewat';
        }

        return $jenis;
    }

    public static function jenispelajar($id)
    {
        if ($id == 1) {
            $jenis = 'Pelajar Baru';
        }
        elseif ($id == 2) {
            $jenis = 'Pelajar Lama';
        }
        elseif ($id == 3) {
            $jenis = 'Pelajar Lewat';
        }

        return $jenis;
    }
}

modules/kewangan/models/YuranPendaftaranDetail.php
<?php

namespace app\modules\kewangan\models;

use Yii;
use app\models\LookupYurandaftar;

/**
 * This is the model class for table "yuran_pendaftaran_detail".
 *
 * @property int $id
 * @property int $item_daftar
 * @property double $price
 * @property double $jumlah
 * @property int $daftarid
 */
class YuranPendaftaranDetail extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'yuran_pendaftaran_detail';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['item_daftar', 'daftarid','status_pay','payment_id'], 'integer'],
            [['price', 'jumlah'], 'number'],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'item_daftar' => 'Item Daftar',
            'price' => 'Price',
            'jumlah' => 'Jumlah',
            'daftarid' => 'Daftarid',
        ];
    }

    public function getItemdaftar()
    {
        return $this->hasOne(LookupYurandaftar::className(),['id'=>'item_daftar']);
    }
}

modules/kewangan/views/yuran-pendaftaran/daftaryuran/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\hr\staff\models\MaklumatKakitanganSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
]); ?>
<div class="card mb-4">
    <div class="card-body">
        <div class="input-group">
            <input type="text" id="yuranpendaftaransearch-globalyuran" class="form-control" name="YuranPendaftaranSearch[globalyuran]" placeholder="Carian..." aria-describedby="basic-addon2" autocomplete="off">

            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Carian</button>
                <?= Html::a('Reset', ['index'], ['class' => 'btn btn-outline-secondary']) ?>

            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

modules/kewangan/views/yuran-pendaftaran/daftaryuran/payyuran.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

use app\modules\kewangan\models\YuranPendaftaran;

$this->title = 'Yuran Pendaftaran Invois - '.$model->invoice_no;

$script = <<< JS
$(document).ready(function(){
	if($('#yurandaftar').hasClass('yuran-pendaftaran/payyuran')){
        $('.main-menu > .scroll > ul > li#kewangan').addClass('active');
        $('.main-menu > .scroll > ul > li#utama').removeClass('active');
    }

    $('.modaltest').click(function(){
        $('#exampleModal').modal('show')
        .find('#modalContent')
        .load($(this).attr('value'));

    });

    deleteswal();
    janaswal();

    function deleteswal(){
        $('a.delete').on('click', function(e){
             e.preventDefault();
            var link = $(this).attr('value');
            console.log(link);
          swal({   
            title: "Anda pasti mahu hapus item ini dari sistem ?",
            // text: "Perhatian ! Proses ini tidak boleh diulang semua !",   
            type: "warning",   
            allowOutsideClick: false,
            showConfirmButton: true,
            showCancelButton: true,
            closeOnConfirm: true,
            closeOnCancel: true,
            confirmButtonText: 'Ya, saya pasti.',
            confirmButtonClass: 'btn-info',
            cancelButtonText: 'Batal',
            cancelButtonClass: 'btn-danger',

          }, 
           function(){   
                // $("#myform").submit();
                $.ajax({
                    type: 'POST',
                    url: link,
                    success: function(data) {
                    
                   }
                });
            });
        })
    }

    //jana yuran
    function janaswal(){
        $('a.jana').on('click', function(e){
             e.preventDefault();
            var link = $(this).attr('value');
            console.log(link);
          swal({   
            title: "Klik YA jika mahu meneruskan transaksi/proses ini.",
            type: "warning",   
            allowOutsideClick: false,
            showConfirmButton: true,
            showCancelButton: true,
            closeOnConfirm: true,
            closeOnCancel: true,
            confirmButtonText: 'Ya',
            confirmButtonClass: 'btn-success',
            cancelButtonText: 'Batal',
            cancelButtonClass: 'btn-danger',

          }, 
           function(){   
                $.ajax({
                    type: 'POST',
                    url: link,
                    success: function(data) {
                    
                   }
                });
            });
        })
    }
});
JS;
$this->registerJs($script);
?>

<span id="yurandaftar" class="<?php echo Yii::$app->controller->id."/".Yii::$app->controller->action->id;?>"></span>
<div class="row">
    <div class="col-12">
        <div class="mb-1">
            <h1><?= Html::encode($this->title) ?></h1>
            <div class="float-md-right text-zero">
                <?= Html::a('Kembali',['index'],['class'=>'btn btn-outline-primary btn-lg']) ?>
            </div>
        </div>

        <div class="separator mb-5"></div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <?php if(Yii::$app->session->hasFlash('savedone')) { ?>
            <div class="alert alert-success" role="alert" id="messageerror2">
                <?php echo Yii::$app->session->getFlash('savedone'); ?>
            </div>
        <?php } ?>
    </div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="box box-success invoice">
			<div id="badge">
                <div class="arrow-up"></div>
                <div class="label bg-aqua"><center><b><?= $model->status ?></b></center></div>
                <div class="arrow-right"></div>
            </div>
			<div class="row invoice-header">
				<div class="col-xs-7">
					<?= Html::img(Yii::getAlias('@web').'/image/logotafhim_1.png',['class'=>'invoice-logo']);  ?>
				</div>
				<div class="col-xs-5 invoice-company"">
					<address>
                        <strong>TAFHIM SDN BHD (560472-M) </strong><br>
                        No. 9, Jalan  1/4, Seksyen 1,<br>
                        43650 Bandar Baru Bangi, Selangor.<br>
                        <br>
                        Tel : 03-89258486 <span>&nbsp;&nbsp;&nbsp;&nbsp;</span> Fax : 03-89127784
                    </address>
				</div>
            </div>
			<div class="box-body">
				<div class="row">
					<div class="col-xs-7">
						Kepada :
						<address>
							<strong><?= $model->namastd->nama_pelajar ?></strong>
							<br>
							<?= $model->namastd->alamat_rumah ?>
						</address>
						<br>
						<span><b>Jenis Pelajar: </b><?= $jenis = YuranPendaftaran::jenispelajar($model->jenis_pelajar) ?></span>
						<br>
						<span><b>Tahap Semasa: </b><?= $model->tahap_pelajar; ?></span>
						<br>
						<span><b>Pusat Pengajian: </b><?= $model->namatahfiz->pusat_pengajian ?></span>
						<div class="mb-5"></div>
					</div>
                	<div class="col-xs-5">
                		<div class="table-responsive">
                			<table class="table no-border">
                				<tbody>
                					<tr>
                						<th class="">No. Invois:</th>
                						<td><?= $model->invoice_no ?></td>
                					</tr>
                					<tr>
                						<th>Tarikh Invois:</th>
                						<td><?= date('d M Y',strtotime($model->created_at)) ?></td>
                					</tr>
                				</tbody>
                			</table>
                		</div>
                	</div>
				</div>
				<div class="row">
	                <div class="col-xs-12 table-responsive">
	                    <table class="table table-striped">
	                    	<thead>
	                    		<?php $model->status_yuran == 1 || $model->status_yuran == 2 || $model->status_yuran == 3 ? $hide = 'style=display:none' : $hide = '' ?>
	                    		<tr>
	                    			<th <?php echo $hide ?>>Tindakan</th>
	                    			<th>Item</th>
	                    			<th>Jumlah (RM)</th>
	                    		</tr>
	                    	</thead>
	                    	<tbody>
	                    		<?php $gross = 0; ?>
	                    		
	                    		<?php foreach ($model->details as $key => $value): ?>
	                    			<tr>
	                    				<td <?php echo $hide ?>>
	                    					<?= Html::a('<i class="iconsmind-Trash-withMen" style="font-size:18px"></i>',FALSE,['value'=>Url::to(['padamitemyuran','id'=>base64_encode($value->id)]),'class' => 'btn btn-xs btn-danger delete','title' => 'Padam Item','data-toggle'=>'tooltip','data-placement'=>'bottom','style'=>'color:#fff']) ?>
	                    					</td>
	                    				<td>
                                            <?= $value->itemdaftar->jenis_bayaran ?>
                                            <br>
                                            <?= $value->item_daftar == 25 ? $model->ulasan_pelarasan : '' ?> 
                                        </td>
	                    				<td><?= number_format($value->price,2) ?></td>
	                    			</tr>
	                    			<?php $gross += $value->price; ?>
	                    		<?php endforeach ?>
	                    		<tr>
	                    			<td <?php echo $hide ?>></td>
	                    			<td align="right"><b>Jumlah Yuran </b></td>
	                    			<td><?= number_format($gross,2) ?></td>
	                    		</tr>
	                    		 <?php if ($model->status_yuran != 0 && $model->status_yuran != 1): ?>
                                     <tr>
                                        <td <?php echo $hide ?>></td>
                                        <td align="right"><b>Amaun Dibayar</b></td>
                                        <td>(<?= $model->jumlah_bayaran != 0.00 ? number_format($model->jumlah_bayaran,2) : '0.00' ?>)</td>
                                    </tr>
                                    <tr>
                                        <td <?php echo $hide ?>></td>
                                        <td align="right"><b>Jumlah Bersih</b></td>
                                        <td>
                                            <?= number_format($model->bakitunggak,2) ?>
                                        </td>
                                    </tr>
                                 <?php endif ?>
	                    	</tbody>
	                    </table>
	                </div>
	            </div>
			</div>
            <div class="box-footer row no-print">
            	<div class="col-md-12">
            		<?php if ($model->status_yuran != 1 && $model->status_yuran != 2 && $model->status_yuran != 3) { ?>
            		<?= Html::a('Kemaskini Yuran',FALSE,['value'=>Url::to(['edityuran','id'=>base64_encode($model->id)]),'class' => 'btn btn-info mb-1 modaltest','id'=>'modaltest']) ?>
            		<?= Html::a('Jana Invois Yuran',FALSE,['value'=>Url::to(['janadaftar','id'=>base64_encode($model->id),'refer'=>'jana']),'class' => 'btn btn-success jana','style'=>'color:#fff']) ?>
                    <?= Html::a('Jana Dan Bayar Yuran',FALSE,['value'=>Url::to(['janadaftar','id'=>base64_encode($model->id)]),'class' => 'btn btn-primary jana','style'=>'color:#fff']) ?>
            	<?php }else{ ?>
            		<button id="btnGroupDrop1" type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tindakan</button>
                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        <?= Html::a('Print',['printinv','id'=>base64_encode($model->id)],['class'=>'dropdown-item','target'=>'_BLANK']) ?>
                        <?php if($model->status_yuran != 3){ ?>
                        <?= Html::a('Tambah Pembayaran',['paymentprocess','id'=>base64_encode($model->id)],['class'=>'dropdown-item']) ?>
                        <?php } ?>
                        <?= Html::a('Pelarasan',['pelarasan','id'=>base64_encode($model->id)],['class'=>'dropdown-item']) ?>
                    </div>
            	<?php } ?>
            	</div>
            </div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="box box-danger invoice">
			<div class="box-title">
				<h4>Rekod Pembayaran</h4>
			</div>
			<div class="box-body table-responsive">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Tarikh</th>
							<th>No Resit</th>
							<th>Ulasan</th>
							<th>Jumlah (RM)</th>
							<th>Tindakan</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($model->payments as $key => $value): ?>
							<tr>
								<td><?= date('d-M-Y',strtotime($value->tarikh_bayaran)) ?></td>
								<td><?= $value->no_resit ?></td>
								<td><?= $value->ulasan ?></td>
								<td><?= number_format($value->jumlah_bayaran,2) ?></td>
								<td><?= Html::a('Print Resit',['printresit','id'=>base64_encode($value->id)],['class'=>'btn btn-outline-primary','target'=>'_BLANK']) ?></td>
							</tr>
						<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

modules/kewangan/views/yuran-pendaftaran/daftaryuran/printresit.php
<?php 
use yii\helpers\Html;

?>

<div class="row text" style="margin:0px;">
	<div class="col-xs-12">
		<div style="border-bottom: 1px solid #dcdcdc;padding: 10px;">
			<div class="col-xs-6">
				<?= Html::img(Yii::getAlias('@web').'/image/logotafhim_1.png',['class'=>'invoice-logo']);  ?>
			</div>
			<div class="col-xs-pull-8">
				<address>
                    <strong>TAFHIM SDN BHD (560472-M) </strong><br>
                    No. 9, Jalan  1/4, Seksyen 1,<br>
                    43650 Bandar Baru Bangi, Selangor.<br>
                    <br>
                    Tel : 03-89258486
                    <br>
                    Fax : 03-89127784
                </address>
                
			</div>
		</div>
		<div style='margin:0 auto;width: 400px;text-align: center;'>
			<h3 style="font-size: 18px"><b>Yuran Pendaftaran</b></h3>
			
		</div>
	</div>
</div>
<div class="row text">
	<div style="padding: 10px;">
		<div class="col-xs-6">
			Bayar Kepada
			<address>
				<strong><?= $model->inv->namastd->nama_pelajar ?></strong>
				<br>
				<?= $model->inv->namastd->alamat_rumah ?>
			</address>
		</div>	
		<div class="col-xs-pull-6">
			<div class="table-responsive">
    			<table class="table no-border text" >
    				<tbody>
    					<tr>
    						<th style="border-top:none;">No. Invois:</th>
    						<td style="border-top:none;"><?= $model->inv->invoice_no ?></td>
    					</tr>
    					<tr>
    						<th style="border-top:none;">Tarikh Invois:</th>
    						<td style="border-top:none;"><?= date('d M Y',strtotime($model->inv->created_at)) ?></td>
    					</tr>
    					<tr>
    						<th style="border-top: none;">No. Resit:</th>
    						<td style="border-top:none;"><?= $model->no_resit ?></td>
    					</tr>
    					<tr>
    						<th style="border-top: none;">Tarikh Bayaran:</th>
    						<td style="border-top: none;"><?= date('d M Y',strtotime($model->tarikh_bayaran)) ?></td>
    					</tr>
    				</tbody>
    			</table>
    		</div>
		</div>
	</div>
</div>
<div class="row text">
	<div class="col-xs-12">
		<table class="table table-striped txttable" style="border-color: 1px solid #908d8d !important;font-family: Courier !important;"  >
			<thead>
				<tr style="background-color: #f9f9f9 !important;"> 
					<th width="5">#</th>
					<th width="550">Item</th>
					<th>Jumlah (RM)</th>
				</tr>
			</thead>
			<tbody>
	           	<?php $gross = 0; ?>

				<?php foreach ($model->itempays as $key => $value): ?>
					<tr>
						<td><?= $key+1 ?></td>
						<td><?= $value->itemdaftar->jenis_bayaran ?></td>
						<td><?= number_format($value->price,2) ?></td>
					</tr>
					<?php $gross += $value->price; ?>

				<?php endforeach ?>
				<tr>
        			<td align="right" colspan="2"><b>Jumlah </b></td>
        			<td><?= number_format($gross,2) ?></td>
        		</tr>
        		<tr>
        			<td align="right" colspan="2"><b>Jumlah Diterima</b></td>
        			<td><?= $model->jumlah_bayaran != 0.00 ? number_format($model->jumlah_bayaran,2) : '0.00' ?></td>
        		</tr>
			</tbody>
		</table>
		<p style="margin-top: 55px;text-align: center;"><b><i>Terima kasih atas pembayaran anda.</i></b></p>
	</div>
</div>