modules/hr/pelajar/models/Zakat.php
<?php

namespace app\modules\hr\pelajar\models;

use Yii;

/**
 * This is the model class for table "zakat".
 *
 * @property int $id
 * @property int $id_pelajar
 * @property int $tahun
 * @property string $date_added
 * @property int $enter_by
 * @property string $jumlah_zakat
 * @property string $nota
 */
class Zakat extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'zakat';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_pelajar'],'required','message'=>'Ruangan {attribute} wajib diisi'],
            [['id_pelajar', 'tahun', 'enter_by','update_by'], 'integer'],
            [['jumlah_zakat'], 'number','message'=>'{attribute} mestilah nombor.'],
            [['date_added','date_update'], 'string', 'max' => 50],
            [['nota'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_pelajar' => 'Nama Pelajar',
            'tahun' => 'Tahun',
            'date_added' => 'Date Added',
            'enter_by' => 'Enter By',
            'jumlah_zakat' => 'Jumlah Zakat',
            'nota' => 'Nota',
        ];
    }

    public function getNamapelajar()
    {
        return $this->hasOne(MaklumatPelajarPenjaga::className(), ['id' => 'id_pelajar']);
    }
}

modules/hr/pelajar/controllers/ZakatController.php
<?php

namespace app\modules\hr\pelajar\controllers;

use Yii;
use app\modules\hr\pelajar\models\Zakat;
use app\modules\hr\pelajar\models\ZakatSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ZakatController implements the CRUD actions for Zakat model.
 */
class ZakatController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Zakat models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ZakatSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Zakat model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel(base64_decode($id)),
        ]);
    }

    /**
     * Creates a new Zakat model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Zakat();

        if ($model->load(Yii::$app->request->post()) ) {
            $model->date_added = date('Y-m-d h:i:s A');
            $model->enter_by = Yii::$app->user->identity->id;
            $model->tahun = $_POST['Zakat']['tahun'];

            if ($model->save()) {
                Yii::$app->session->setFlash('savedone','Maklumat zakat telah berjaya disimpan');
                return $this->redirect(['view','id'=>base64_encode($model->id)]);
            }
        }

        return $this->render('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Zakat model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel(base64_decode($id));

        if ($model->load(Yii::$app->request->post()) ) {
            $model->date_update = date('Y-m-d h:i:s A');
            $model->update_by = Yii::$app->user->identity->id;
            $model->tahun = $_POST['Zakat']['tahun'];

            if ($model->save()) {
                Yii::$app->session->setFlash('savedone','Maklumat zakat telah berjaya dikemaskini');
                return $this->redirect(['view','id'=>base64_encode($model->id)]);
            }
        }

        return $this->render('edit', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Zakat model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel(base64_decode($id))->delete();
        Yii::$app->session->setFlash('savedone','Maklumat zakat telah berjaya dihapus');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Zakat model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Zakat the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Zakat::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/hr/pelajar/views/zakat/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

use app\modules\hr\pelajar\models\MaklumatPelajarPenjaga;

$nama = ArrayHelper::map(MaklumatPelajarPenjaga::find()->where(['alumni'=>0])->andWhere(['status_deleted'=>2])->asArray()->orderBy(['nama_pelajar'=>SORT_ASC])->all(),'id','nama_pelajar'); //retrieve data for dropdown

/* @var $this yii\web\View */
/* @var $model app\modules\hr\pelajar\models\Zakat */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'Tambah Zakat';

$script = <<< JS
$(document).ready(function(){
    if($('#pelajar').hasClass('zakat/create')){
        $('.main-menu > .scroll > ul > li#hr').addClass('active');
        $('.main-menu > .scroll > ul > li#utama').removeClass('active');
    }

});
JS;
$this->registerJs($script);
?>
<span id="pelajar" class="<?php echo Yii::$app->controller->id."/".Yii::$app->controller->action->id;?>"></span>
<div class="row">
    <div class="col-12">
        <div class="mb-1">
            <h1><?= Html::encode($this->title) ?></h1>
            <div class="float-md-right text-zero">
                <?= Html::a('Kembali',['index'],['class'=>'btn btn-outline-primary btn-lg']) ?>
            </div>
        </div>
        <div class="separator mb-5"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box box-danger">
            <?php $form = ActiveForm::begin(); ?>
            <div class="box-body">
                <div class="">
                    <h5 class="mb-4">Maklumat Zakat</h5>
                    <?= $form->errorSummary($model,['class'=>'alert alert-danger','header'=>'']); ?>
                    <form>
                         <div class="form-row">
                             <div class="form-group col-md-4">
                                <label>Nama Pelajar</label>
                                <?= $form->field($model, 'id_pelajar')->dropDownList($nama, 
                                    [
                                        'prompt'=>'Sila Pilih',
                                        'class'=>'select2-single'
                                    ]
                                    )->label(false) ?>
                             </div>
                             <div class="form-group col-md-4">
                                 <label>Pilih Tahun</label>
                                 <select name="Zakat[tahun]" class="form-control" required="">
                                    <?php 
                                        $already_selected_value = date('Y');
                                        $earliest_year = 2016;
                                        foreach (range(date('Y'), $earliest_year) as $x) {
                                            print '<option value="'.$x.'"'.($x === $already_selected_value ? ' selected="selected"' : '').'>'.$x.'</option>';
                                        }
                                    ?>
                                </select>
                             </div>
                             <div class="form-group col-md-4">
                                <label>Jumlah Zakat</label>
                                <?= $form->field($model, 'jumlah_zakat')->textInput(['maxlength' => true])->label(false) ?>
                             </div>
                         </div>
                         <div class="form-row">
                             <div class="form-group col-md-12">
                                <label>Nota</label>
                                <?= $form->field($model, 'nota')->textArea(['rows'=>6])->label(false) ?>

                             </div>
                         </div>
                    </form>
                </div>
                <div class="box-footer">
                    <div class="col-md-12">
                        <?= $form->errorSummary($model,['class'=>'alert alert-danger','header'=>'']); ?>

                        <?= Html::submitButton('Simpan', ['class' => 'btn btn-success mb-1']) ?>

                        <?= Html::a('Batal',['index'],['class'=>'btn btn-danger mb-1']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/hr/pelajar/views/zakat/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\hr\staff\models\MaklumatKakitanganSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
]); ?>
<div class="card mb-4">
    <div class="card-body">
        <div class="input-group">
            <input type="text" id="zkatsearch-globalzakat" class="form-control" name="ZakatSearch[globalzakat]" placeholder="Carian..." aria-describedby="basic-addon2" autocomplete="off">

            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Carian</button>
                <?= Html::a('Reset', ['index'], ['class' => 'btn btn-outline-secondary']) ?>

            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

modules/hr/pelajar/views/zakat/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\hr\pelajar\models\Zakat */

$this->title = 'Create Zakat';
$this->params['breadcrumbs'][] = ['label' => 'Zakats', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="zakat-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/hr/pelajar/views/zakat/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

use app\modules\hr\pelajar\models\MaklumatPelajarPenjaga;

$nama = ArrayHelper::map(MaklumatPelajarPenjaga::find()->where(['alumni'=>0])->andWhere(['status_deleted'=>2])->asArray()->orderBy(['nama_pelajar'=>SORT_ASC])->all(),'id','nama_pelajar'); //retrieve data for dropdown

/* @var $this yii\web\View */
/* @var $model app\modules\hr\pelajar\models\Zakat */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'Tambah Zakat';

$script = <<< JS
$(document).ready(function(){
    if($('#pelajar').hasClass('zakat/create')){
        $('.main-menu > .scroll > ul > li#hr').addClass('active');
        $('.main-menu > .scroll > ul > li#utama').removeClass('active');
    }

});
JS;
$this->registerJs($script);
?>
<span id="pelajar" class="<?php echo Yii::$app->controller->id."/".Yii::$app->controller->action->id;?>"></span>
<div class="row">
    <div class="col-12">
        <div class="mb-1">
            <h1><?= Html::encode($this->title) ?></h1>
            <div class="float-md-right text-zero">
                <?= Html::a('Kembali',['index'],['class'=>'btn btn-outline-primary btn-lg']) ?>
            </div>
        </div>
        <div class="separator mb-5"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box box-danger">
            <?php $form = ActiveForm::begin(); ?>
            <div class="box-body">
                <div class="">
                    <h5 class="mb-4">Maklumat Zakat</h5>
                    <?= $form->errorSummary($model,['class'=>'alert alert-danger','header'=>'']); ?>
                    <form>
                         <div class="form-row">
                             <div class="form-group col-md-4">
                                <label>Nama Pelajar</label>
                                <?= $form->field($model, 'id_pelajar')->dropDownList($nama, 
                                    [
                                        'prompt'=>'Sila Pilih',
                                        'class'=>'select2-single'
                                    ]
                                    )->label(false) ?>
                             </div>
                             <div class="form-group col-md-4">
                                 <label>Pilih Tahun</label>
                                 <select name="Zakat[tahun]" class="form-control" required="">
                                    <?php 
                                        $already_selected_value = $model->tahun;
                                        $earliest_year = 2016;
                                        foreach (range(date('Y'), $earliest_year) as $x) {
                                            print '<option value="'.$x.'"'.($x === $already_selected_value ? ' selected="selected"' : '').'>'.$x.'</option>';
                                        }
                                    ?>
                                </select>
                             </div>
                             <div class="form-group col-md-4">
                                <label>Jumlah Zakat</label>
                                <?= $form->field($model, 'jumlah_zakat')->textInput(['maxlength' => true])->label(false) ?>
                             </div>
                         </div>
                         <div class="form-row">
                             <div class="form-group col-md-12">
                                <label>Nota</label>
                                <?= $form->field($model, 'nota')->textArea(['rows'=>6])->label(false) ?>

                             </div>
                         </div>
                    </form>
                </div>
                <div class="box-footer">
                    <div class="col-md-12">
                        <?= $form->errorSummary($model,['class'=>'alert alert-danger','header'=>'']); ?>

                        <?= Html::submitButton('Simpan', ['class' => 'btn btn-success mb-1']) ?>

                        <?= Html::a('Batal',['index'],['class'=>'btn btn-danger mb-1']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

modules/hr/pelajar/views/zakat/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\modules\hr\pelajar\models\ZakatSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Zakat Pelajar';
$this->params['breadcrumbs'][] = $this->title;

$script = <<< JS
$(document).ready(function(){
    if($('#zakat').hasClass('zakat/index')){
        $('.main-menu > .scroll > ul > li#hr').addClass('active');
        $('.main-menu > .scroll > ul > li#utama').removeClass('active');
    }

    deleteswal();
    $("#some_pjax_id").on("pjax:success", function() {
      deleteswal();
    });

    function deleteswal(){
        $('a.delete').on('click', function(e){
             e.preventDefault();
            var link = $(this).attr('value');

          swal({   
            title: 'Anda pasti mahu hapus maklumat zakat ini ?',
            // text: "Perhatian ! Proses ini tidak boleh diulang semua !",   
            type: "warning",   
            allowOutsideClick: false,
            showConfirmButton: true,
            showCancelButton: true,
            closeOnConfirm: true,
            closeOnCancel: true,
            confirmButtonText: 'Ya, saya pasti.',
            confirmButtonClass: 'btn-info',
            cancelButtonText: 'Batal',
            cancelButtonClass: 'btn-danger',

          }, 
           function(){   
                // $("#myform").submit();
                $.ajax({
                    type: 'POST',
                    url: link,
                    success: function(data) {
                    
                   }
                });
            });
        })
    }
});
JS;
$this->registerJs($script);
?>
<span id="zakat" class="<?php echo Yii::$app->controller->id."/".Yii::$app->controller->action->id;?>"></span>
<div class="row">
    <div class="col-12">
        <div class="mb-1">
            <h1><?= Html::encode($this->title) ?></h1>
            <div class="float-md-right text-zero">
                <?= Html::a('Tambah Baru',['create'],['class'=>'btn btn-outline-primary btn-lg']) ?>
            </div>
        </div>
        <div class="separator mb-5"></div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?= $this->render('_search', ['model' => $searchModel]);  ?>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php if(Yii::$app->session->hasFlash('savedone')) { ?>
            <div class="alert alert-success" role="alert" id="messageerror2">
                <?php echo Yii::$app->session->getFlash('savedone'); ?>
            </div>
        <?php } ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box box-danger">
            <div class="box-body table-responsive">
                <?php Pjax::begin(['id'=>'some_pjax_id']); ?>
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'layout' => "{summary}\n{items}\n<nav class='mt-4 mb-3'>{pager}</nav>",
                        'pager' => [
                            'firstPageLabel' => 'Mula',
                            'lastPageLabel' => 'Akhir',
                            'prevPageLabel' => 'Sebelumnya',
                            'nextPageLabel' => 'Seterusnya',

                            'maxButtonCount' => 5,

                             'options' => [
                                'tag' => 'ul',
                                'class' => 'pagination justify-content-center mb-0',
                            ],
                            'linkContainerOptions'=>['class'=>'page-item'],
                            'linkOptions' => ['class' => 'page-link'],
                            'activePageCssClass' => 'active',
                        ],
                        'tableOptions'=>['class'=>'table table-striped'],
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],
                                [
                                    'attribute'=>'date_added',
                                    'format'=>'raw',
                                    'value'=>function($data){
                                        return date('d/m/Y',strtotime($data->date_added));
                                    }
                                ],
                                'namapelajar.nama_pelajar',
                                'namapelajar.no_mykid',
                                'tahun',
                                'jumlah_zakat',
                                //'nota',
                            [
                                'header' => 'Tindakan',
                                'class' => 'yii\grid\ActionColumn',
                                'template'=>'{all}',
                                'buttons' => [
                                    'all' => function ($url, $model, $key) {
                                        return ButtonDropdown::widget([
                                            'encodeLabel' => false, // if you're going to use html on the button label
                                            'label' => 'Pilih Tindakan',
                                            'dropdown' => [
                                                'encodeLabels' => false, // if you're going to use html on the items' labels
                                                'items' => [
                                                    [
                                                        'label' => \Yii::t('yii', 'Lihat Maklumat'),
                                                        'url' => ['zakat/view', 'id' =>base64_encode($key)],
                                                        'linkOptions' => ['class'=>'dropdown-item'],
                                                        'visible' => true,  // if you want to hide an item based on a condition, use this
                                                    ],
                                                    [
                                                        'label' => \Yii::t('yii', 'Kemaskini Maklumat'),
                                                        'url' => ['zakat/update', 'id' => base64_encode($key)],
                                                        'linkOptions' => ['class'=>'dropdown-item'],
                                                        'visible' => true,  // if you want to hide an item based on a condition, use this
                                                    ],
                                                    [
                                                        'label' => \Yii::t('yii', 'Hapus'),
                                                        'url'=>FALSE,
                                                        'linkOptions' => ['id'=>'delete','class'=>'dropdown-item delete','value'=>Url::to(['delete','id'=>base64_encode($key)])],
                                                        'visible' => true,  // if you want to hide an item based on a condition, use this
                                                    ],
                                                    
                                                ],
                                                
                                            ],
                                            'options' => [
                                                'class' => 'btn btn-outline-primary btn-sm',   // btn-success, btn-info, et cetera
                                            ],
                                            'split' => false,    // if you want a split button
                                        ]);
                                    },
                                ],
                            ],
                        ],
                    ]); ?>
                <?php Pjax::end(); ?>
            </div>
        </div>
    </div>
</div>

modules/hr/pelajar/views/zakat/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\hr\pelajar\models\Zakat */

$this->title = 'Update Zakat: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Zakats', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="zakat-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/hr/pelajar/views/zakat/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\modules\hr\pelajar\models\Zakat */

$this->title = 'Maklumat Terperinci';

$script = <<< JS
$(document).ready(function(){
    if($('#pelajar').hasClass('zakat/view')){
        $('.main-menu > .scroll > ul > li#hr').addClass('active');
        $('.main-menu > .scroll > ul > li#utama').removeClass('active');
    }

    deleteswal();
    $("#some_pjax_id").on("pjax:success", function() {
      deleteswal();
    });

    function deleteswal(){
        $('a.delete').on('click', function(e){
             e.preventDefault();
            var link = $(this).attr('value');

          swal({   
            title: 'Anda pasti mahu hapus maklumat zakat ini ?',
            // text: "Perhatian ! Proses ini tidak boleh diulang semua !",   
            type: "warning",   
            allowOutsideClick: false,
            showConfirmButton: true,
            showCancelButton: true,
            closeOnConfirm: true,
            closeOnCancel: true,
            confirmButtonText: 'Ya, saya pasti.',
            confirmButtonClass: 'btn-info',
            cancelButtonText: 'Batal',
            cancelButtonClass: 'btn-danger',

          }, 
           function(){   
                // $("#myform").submit();
                $.ajax({
                    type: 'POST',
                    url: link,
                    success: function(data) {
                    
                   }
                });
            });
        })
    }
});
JS;
$this->registerJs($script);
?>
<span id="pelajar" class="<?php echo Yii::$app->controller->id."/".Yii::$app->controller->action->id;?>"></span>
<div class="row">
    <div class="col-12">
        <div class="mb-1">
            <h1><?= Html::encode($this->title) ?></h1>
            <div class="float-md-right text-zero">
                <?= Html::a('Kembali',['index'],['class'=>'btn btn-outline-primary btn-lg mr-1']) ?>
                <button class="btn btn-outline-primary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pilih Tindakan
                </button>
                <div class="dropdown-menu" x-placement="top-start" style="position: absolute; transform: translate3d(0px, -105px, 0px); top: 0px; left: 0px; will-change: transform;">
                    <?= Html::a('Tambah Baru',['create'],['class'=>'dropdown-item']) ?>
                    <?= Html::a('Kemaskini Maklumat',['update','id'=>base64_encode($model->id)],['class'=>'dropdown-item']) ?>
                    <?= Html::a('Hapus',FALSE,['class'=>'dropdown-item delete','id'=>'','value'=>Url::to(['delete','id'=>base64_encode($model->id)])]) ?>
                </div>
            </div>
        </div>
        <div class="separator mb-5"></div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php if(Yii::$app->session->hasFlash('savedone')) { ?>
            <div class="alert alert-success" role="alert" id="messageerror2">
                <?php echo Yii::$app->session->getFlash('savedone'); ?>
            </div>
        <?php } ?>
    </div>
</div>

<div class="row">
    <div class="col-12 mb-4">
        <div class="box box-danger">
            <div class="card-body">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'namapelajar.nama_pelajar',
                        'tahun',
                        'date_added',
                        'enter_by',
                        'jumlah_zakat',
                        'nota',
                    ],
                ]) ?>
            </div>
        </div>
    </div>
</div>