modules/hr/pelajar/models/MaklumatPilihanPusatPengajian.php
<?php

namespace app\modules\hr\pelajar\models;

use Yii;
use app\models\LookupPusatPengajian;

/**
 * This is the model class for table "maklumat_pilihan_pusat_pengajian".
 *
 * @property integer $id
 * @property integer $nama_pusat_pengajian_pertama
 * @property integer $nama_pusat_pengajian_kedua
 * @property integer $nama_pusat_pengajian_ketiga
 * @property string $sessi_pengajian
 * @property string $id_pelajar
 */
class MaklumatPilihanPusatPengajian extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'maklumat_pilihan_pusat_pengajian';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['nama_pusat_pengajian_pertama', 'required', 'message' => 'Ruangan {attribute} wajib diisi'],

            [['nama_pusat_pengajian_pertama', 'nama_pusat_pengajian_kedua', 'nama_pusat_pengajian_ketiga'], 'integer'],
            [['id_pelajar','sessi_pengajian'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_pusat_pengajian_pertama' => 'Pilih Pusat Pengajian Pertama',
            'nama_pusat_pengajian_kedua' => 'Pilih Pusat Pengajian Kedua',
            'nama_pusat_pengajian_ketiga' => 'Pilih Pusat Pengajian Ketiga',
            'sessi_pengajian' => 'Sesi Pengajian',
            'id_pelajar' => 'Id Pelajar',
        ];
    }


    public function getPertama()
    {
        return $this->hasOne(LookupPusatPengajian::className(), ['id' => 'nama_pusat_pengajian_pertama']);
    }
    public function getKedua()
    {
        return $this->hasOne(LookupPusatPengajian::className(), ['id' => 'nama_pusat_pengajian_kedua']);
    }
    public function getKetiga()
    {
        return $this->hasOne(LookupPusatPengajian::className(), ['id' => 'nama_pusat_pengajian_ketiga']);
    }
    
}

modules/hr/pelajar/controllers/MaklumatPelajarPenjagaController.php
<?php

namespace app\modules\hr\pelajar\controllers;

use Yii;
use app\modules\hr\pelajar\models\MaklumatPelajarPenjaga;
use app\modules\hr\pelajar\models\PusatPendaftaran;
use app\modules\hr\pelajar\models\MaklumatPilihanPusatPengajian;
use app\modules\hr\pelajar\models\MaklumatPelajarPenjagaSearch;
use app\modules\kewangan\models\YuranPendaftaran;
use app\modules\kewangan\models\YuranPendaftaranDetail;
use app\modules\kewangan\models\YuranPendaftaranSearch;
use app\modules\kewangan\models\YuranPaymentDetails;
use app\models\LookupYurandaftar;

use app\models\LookupDistrict;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;

/**
 * MaklumatPelajarPenjagaController implements the CRUD actions for MaklumatPelajarPenjaga model.
 */
class MaklumatPelajarPenjagaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MaklumatPelajarPenjaga models.
     * @return mixed
     */

    /** ALL **/
    public function actionAll()
    {
        $searchModel = new MaklumatPelajarPenjagaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider->query->andWhere(['maklumat_pelajar_penjaga.status_deleted'=>2]);

        return $this->render('senarai_keseluruhan',[
            'searchModel'=>$searchModel,
            'dataProvider'=>$dataProvider,
        ]);
    }
    /** END ALL **/
    public function actionIndex()
    {
        $searchModel = new MaklumatPelajarPenjagaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        $dataProvider->query->andWhere(['maklumat_pelajar_penjaga.pusat_pengajian_id'=>Yii::$app->user->identity->tahfiz]);
        $dataProvider->query->andWhere(['maklumat_pelajar_penjaga.alumni'=>0]);
        $dataProvider->query->andWhere(['maklumat_pelajar_penjaga.status_deleted'=>2]);

        return $this->render('aktif/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MaklumatPelajarPenjaga model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('aktif/view', [
            'model' => $this->findModel(base64_decode($id)),
        ]);
    }

    /**
     * Creates a new MaklumatPelajarPenjaga model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MaklumatPelajarPenjaga();
        $model3 = new PusatPendaftaran();
        $model2 = new YuranPendaftaran();
        $model4 = new YuranPendaftaranDetail();

        $model->scenario = 'registerday';
        $model2->scenario = 'yuranregisterday';
        
        if($model->load(Yii::$app->request->post()) && $model3->load(Yii::$app->request->post()) && $model2->load(Yii::$app->request->post()) )
        {
            //identify dlu user key in no mykid atau no passport
            if ($_POST['optionidentity'] == 'mykid') {

                $lengnama = str_replace('_', '', $model->no_mykid);
                if(strlen($lengnama) == 14){
                    
                }
                else{
                    Yii::$app->session->setFlash('saveerror','Nombor mykid pelajar perlu mengikut format di tetapkan seperti 123456-78-9101');
                    
                    return $this->redirect(Yii::$app->request->referrer);
                }
            }
            else{
                //do nothing
                // $model->no_mykid = $model->passport;
            }
            
            $model->status="Approved";
            $model->date_create = date('Y-m-d h:i:s A');
            $model->enter_by = Yii::$app->user->identity->id;
            $model->pusat_pendaftaran = $model3->pusat_pendaftaran;
            $model->tahap_semasa = $model->tahun_mula;
            $model->nama_pelajar = strtoupper($_POST["MaklumatPelajarPenjaga"]["nama_pelajar"]);

            if($model->save()){
                //save bill
                $bill = YuranPendaftaran::savebill($model->id,$model2->jenis_pelajar);

                $last_id = Yii::$app->db->getLastInsertID();
                
                $model3->id_pelajar = $last_id;
                $model3->save();

                if ($_POST['optionyuran'] == 'Ya') {
                    Yii::$app->session->setFlash('savedone','Maklumat pelajar telah berjaya disimpan. Maklumat dibawah adalah invois yuran pendaftaran.');
                    return $this->redirect(['/kewangan/yuran-pendaftaran/payyuran','id'=>base64_encode($bill)]);
                }
                else{
                    Yii::$app->session->setFlash('savedone','Maklumat pelajar telah berjaya disimpan');
                    return $this->redirect(['create']);
                }
                
            }
        }
        else{
            return $this->render('aktif/_form', [
                'model' => $model,
                'model3' => $model3,
                'model2'=>$model2,
            ]);
        }        
    }

    public function actionExistdata($id)
    {
        $model = MaklumatPelajarPenjaga::findOne($id);

        $model2 = new YuranPendaftaran();
        $model4 = new YuranPendaftaranDetail();

        $model->scenario = 'registerday_existdata';
        $model2->scenario = 'yuranregisterday';

        if ($model->load(Yii::$app->request->post()) && $model2->load(Yii::$app->request->post())) {

            //identify dlu user key in no mykid atau no passport
            if ($_POST['optionidentity'] == 'mykid') {

                $lengnama = str_replace('_', '', $model->no_mykid);
                if(strlen($lengnama) == 14){
                    #do nothing
                }
                else{
                    Yii::$app->session->setFlash('saveerror','Nombor mykid pelajar perlu mengikut format di tetapkan seperti 123456-78-9101');
                    
                    return $this->redirect(Yii::$app->request->referrer);
                }
            }
            else{
                //do nothing
                // $model->no_mykid = $model->passport;
            }
            
            $model->date_update = date('Y-m-d h:i:s A');
            $model->update_by = Yii::$app->user->identity->id;
            $model->nama_pelajar = strtoupper($_POST["MaklumatPelajarPenjaga"]["nama_pelajar"]);

            if ($model->save()) {
                //save bill
                $bill = YuranPendaftaran::savebill($model->id,$model2->jenis_pelajar);

                if ($_POST['optionyuran'] == 'Ya') {
                    Yii::$app->session->setFlash('savedone','Maklumat pelajar telah berjaya disimpan. Maklumat dibawah adalah invois yuran pendaftaran.');
                    return $this->redirect(['/kewangan/yuran-pendaftaran/payyuran','id'=>base64_encode($bill)]);
                }
                else{
                    Yii::$app->session->setFlash('savedone','Maklumat pelajar telah berjaya disimpan');
                    return $this->redirect(['create']);
                }
            }
        }
        else{
            return $this->render('aktif/existdata',[
                'model'=>$model,
                'model2'=>$model2,
                // 'model4'=>$model4,
            ]);
        }
    }
    /**
     * Updates an existing MaklumatPelajarPenjaga model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = MaklumatPelajarPenjaga::find()
            ->where(['id'=>base64_decode($id)])
            ->one();

        if($model->load(Yii::$app->request->post()) )
        {

            if ($_POST['optionidentity'] == 'mykid') {

                $lengnama = str_replace('_', '', $model->no_mykid);
                if(strlen($lengnama) == 14){
                    
                }
                else{
                    Yii::$app->session->setFlash('saveerror','Nombor mykid pelajar perlu mengikut format di tetapkan seperti 123456-78-9101');
                    
                    return $this->redirect(Yii::$app->request->referrer);
                }
            }
            else{
                //do nothing
            }
            $model->date_update = date('Y-m-d h:i:s A');
            $model->update_by = Yii::$app->user->identity->id;
            // $model->sesi_pengajian = $model2->sessi_pengajian;

            if($model->save()){
               Yii::$app->session->setFlash('savedone','Maklumat pelajar telah berjaya dikemaskini');
                return $this->redirect(['view','id'=>base64_encode($model->id)]);        
            }
        }else {
            return $this->render('aktif/edit', [
                'model' => $model,
            ]);
        }
    }  

    public function actionChange_alumni($id)
    {
        $model = $this->findModel(base64_decode($id));

        $model->alumni = '1';
        $model->save();
        if ($model->save()) {
            Yii::$app->session->setFlash('savedone','Maklumat pelajar telah di pindah ke ruangan alumni');
            return $this->redirect(['index']);   
        }
    }

    /**
     * Deletes an existing MaklumatPelajarPenjaga model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */

modules/hr/pelajar/views/maklumat-pelajar-penjaga/hq/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\hr\staff\models\MaklumatKakitanganSearch */
/* @var $form yii\widgets\ActiveForm */
?>
<?php $form = ActiveForm::begin([
    'action' => ['pending'],
    'method' => 'get',
]); ?>
<div class="card mb-4">
    <div class="card-body">
        <div class="input-group">
            <input type="text" id="MaklumatPelajarPenjagaSearch-globalstd" class="form-control" name="MaklumatPelajarPenjagaSearch[globalstd]" placeholder="Carian..." aria-describedby="basic-addon2" autocomplete="off">

            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Carian</button>
                <?= Html::a('Reset', ['pending'], ['class' => 'btn btn-outline-secondary']) ?>

            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

modules/hr/pelajar/views/maklumat-pelajar-penjaga/hq/pending.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\ButtonDropdown;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\modules\hr\pelajar\models\MaklumatPelajarPenjagaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Senarai Pelajar Pending';
$this->params['breadcrumbs'][] = $this->title;

$script = <<< JS
$(document).ready(function(){
    if($('#pelajar').hasClass('maklumat-pelajar-penjaga/pending')){
        $('.main-menu > .scroll > ul > li#hr').addClass('active');
        $('.main-menu > .scroll > ul > li#utama').removeClass('active');
    }

    function init_click_handlers(){
        $('.modaltest').click(function(){
            $('#exampleModal').modal('show')
            .find('#modalContent')
            .load($(this).attr('value'));

        });
    }
    
    init_click_handlers(); //first run
    deleteswal();
    $("#some_pjax_id").on("pjax:success", function() {
      init_click_handlers(); //reactivate links in grid after pjax update
      deleteswal();
    });

    function deleteswal(){
        $('a.delete').on('click', function(e){
             e.preventDefault();
            var link = $(this).attr('value');
            var myId = $(this).attr('id');
            if(myId == 'softdelete'){
                var title = 'Anda pasti mahu hapus maklumat pelajar ini ?';
            }
            else{
                var title = 'Anda pasti mahu pindah pelajar ini ke alumni ?';
            }
            
            console.log(link);
          swal({   
            title: title,
            // text: "Perhatian ! Proses ini tidak boleh diulang semua !",   
            type: "warning",   
            allowOutsideClick: false,
            showConfirmButton: true,
            showCancelButton: true,
            closeOnConfirm: true,
            closeOnCancel: true,
            confirmButtonText: 'Ya, saya pasti.',
            confirmButtonClass: 'btn-info',
            cancelButtonText: 'Batal',
            cancelButtonClass: 'btn-danger',

          }, 
           function(){   
                // $("#myform").submit();
                $.ajax({
                    type: 'POST',
                    url: link,
                    success: function(data) {
                    
                   }
                });
            });
        })
    }
});
JS;
$this->registerJs($script);
?>
<span id="pelajar" class="<?php echo Yii::$app->controller->id."/".Yii::$app->controller->action->id;?>"></span>
<div class="row">
    <div class="col-12">
        <div class="mb-1">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
        <div class="separator mb-5"></div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?= $this->render('_search', ['model' => $searchModel]);  ?>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php if(Yii::$app->session->hasFlash('savedone')) { ?>
            <div class="alert alert-success" role="alert" id="messageerror2">
                <?php echo Yii::$app->session->getFlash('savedone'); ?>
            </div>
        <?php } ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box box-danger">
            <div class="box-body table-responsive">
                <?php Pjax::begin(['id'=>'some_pjax_id']); ?>    
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    // 'filterModel' => $searchModel,
                    'layout' => "{summary}\n{items}\n<nav class='mt-4 mb-3'>{pager}</nav>",
                    'pager' => [
                        'firstPageLabel' => 'Mula',
                        'lastPageLabel' => 'Akhir',
                        'prevPageLabel' => 'Sebelumnya',
                        'nextPageLabel' => 'Seterusnya',

                        'maxButtonCount' => 5,

                         'options' => [
                            'tag' => 'ul',
                            'class' => 'pagination justify-content-center mb-0',
                        ],
                        'linkContainerOptions'=>['class'=>'page-item'],
                        'linkOptions' => ['class' => 'page-link'],
                        'activePageCssClass' => 'active',
                    ],
                    'tableOptions'=>['class'=>'table table-striped'],
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],
                        'nama_pelajar',
                        'tarikh_masuk',
                        'no_mykid',
                        [
                            'attribute'=>'pusat_pendaftaran',
                            'format'=>'raw',
                            'value'=>function($data){
                                return $data->pusat_pendaftaran ? $data->register->pusat_pengajian : '';
                            }
                        ],
                        [
                            'label'=>'Dimasukkan Oleh',
                            'format'=>'raw',
                            'value'=>function($data){
                                return $data->enter_by ? $data->enterby->nama_akaun : '';
                            }
                        ],
                        [
                            'header' => 'Tindakan',
                            'class' => 'yii\grid\ActionColumn',
                            'template'=>'{all}',
                            'buttons' => [
                                'all' => function ($url, $model, $key) {
                                    return ButtonDropdown::widget([
                                        'encodeLabel' => false, // if you're going to use html on the button label
                                        'label' => 'Pilih Tindakan',
                                        'dropdown' => [
                                            'encodeLabels' => false, // if you're going to use html on the items' labels
                                            'items' => [
                                                [
                                                    'label' => \Yii::t('yii', 'Kemaskini Maklumat'),
                                                    'url' => ['maklumat-pelajar-penjaga/updatepending', 'id' =>base64_encode($key)],
                                                    'linkOptions' => ['class'=>'dropdown-item'],
                                                    'visible' => true,  // if you want to hide an item based on a condition, use this
                                                ],
                                                [
                                                    'label' => \Yii::t('yii', 'Status'),
                                                    'url' => ['maklumat-pelajar-penjaga/status', 'id' =>base64_encode($key)],
                                                    'linkOptions' => ['class'=>'dropdown-item'],
                                                    'visible' => true,  // if you want to hide an item based on a condition, use this
                                                ],
                                            ],
                                            
                                        ],
                                        'options' => [
                                            'class' => 'btn btn-outline-primary btn-sm',   // btn-success, btn-info, et cetera
                                        ],
                                        'split' => false,    // if you want a split button
                                    ]);
                                },
                            ],
                        ],

                    ],
                ]); ?>
                <?php Pjax::end(); ?>
            </div>
        </div>
    </div>
</div>

modules/hr/pelajar/views/maklumat-pelajar-penjaga/hq/status.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

use app\models\LookupPusatPengajian;

$this->title = 'Kemaskini Status Pelajar';

$pengajian = ArrayHelper::map(LookupPusatPengajian::find()->asArray()->all(), 'id', 'pusat_pengajian');

$script = <<< JS
$(document).ready(function(){
	if($('#pelajar').hasClass('maklumat-pelajar-penjaga/status')){
        $('.main-menu > .scroll > ul > li#hr').addClass('active');
        $('.main-menu > .scroll > ul > li#utama').removeClass('active');
    }
});
JS;
$this->registerJs($script);
?>
<span id="pelajar" class="<?php echo Yii::$app->controller->id."/".Yii::$app->controller->action->id;?>"></span>
<div class="row">
    <div class="col-12">
        <div class="mb-1">
            <h1><?= Html::encode($this->title) ?></h1>
            <div class="float-md-right text-zero">
                <?= Html::a('Kembali',['pending'],['class'=>'btn btn-outline-primary btn-lg']) ?>
            </div>
        </div>
        <div class="separator mb-5"></div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <?php if(Yii::$app->session->hasFlash('saveerror')) { ?>
            <div class="alert alert-danger" role="alert" id="messageerror2">
                <?php echo Yii::$app->session->getFlash('saveerror'); ?>
            </div>
        <?php } ?>
    </div>
</div>
<div class="row">
    <div class="col-12 col-lg-12">
        <div class="box box-danger">
        	<?php $form = ActiveForm::begin(); ?>
            <div class="box-body">
            	<div class="col-md-12">
            		<h5 class="mb-4">Pilihan Pusat Pengajian</h5>
            		<table class="table table-striped">
            			<tr>
            				<td>Pilihan Pertama</td>
            				<td><?= $model2->nama_pusat_pengajian_pertama ? $model2->pertama->pusat_pengajian : '' ?></td>
            			</tr>
            			<tr>
            				<td>Pilihan Kedua</td>
            				<td><?= $model2->nama_pusat_pengajian_kedua ? $model2->kedua->pusat_pengajian : '' ?></td>
            			</tr>
            			<tr>
            				<td>Pilihan Ketiga</td>
            				<td><?= $model2->nama_pusat_pengajian_ketiga ? $model2->ketiga->pusat_pengajian : '' ?></td>
            			</tr>
            		</table>
            	</div>
            	<div class="separator mb-5"></div>
            	<?= $form->errorSummary($model,['class'=>'alert alert-danger','header'=>'']); ?>
                <form>
                     <div class="form-row">
                     	<div class="form-group col-md-6">
                     		<label>Pusat Pengajian</label>
                     		<?= $form->field($model, 'pusat_pengajian_id')->dropDownList($pengajian, ['prompt' => '--Sila Pilih--'])->label(false) ?>
                        </div>
                        <div class="form-group col-md-6">
                     		<label>Sesi Pengajian</label>
                     		<?= $form->field($model, 'sesi_pengajian')->dropDownList([ 'Pagi' => 'Pagi', 'Petang' => 'Petang', ], ['prompt' => '--Sila Pilih--'])->label(false) ?>
                        </div>
                     </div>
                     <div class="form-row">
                     	<div class="form-group col-md-6">
                     		<label>Status</label>
                     		<?= $form->field($model, 'status')->dropDownList([ 'Approved' => 'Approved', 'Pending' => 'Pending', ], ['prompt' => '--Sila Pilih--'])->label(false) ?>
                        </div>
                        <div class="form-group col-md-6">
                     		<label>Tahun Lewat</label>
                     		<?= $form->field($model, 'tahun_lewat')->dropDownList([ '0' => '--Sila Pilih--', '1' => 'Ya','2' => 'Tidak' ])->label(false) ?>
                        </div>
                     </div>
                </form>
                <div class="box-footer">
                    <div class="col-md-12">
                        <?= $form->errorSummary($model,['class'=>'alert alert-danger','header'=>'']); ?>

                        <?= Html::submitButton('Kemaskini', ['class' => 'btn btn-success mb-1']) ?>

                        <?= Html::a('Batal',['pending'],['class'=>'btn btn-danger mb-1']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>            
        </div>
    </div>
</div>